### ISSUE TITLE
Tinkbox - thumbnails missing in tinkbox - see attachement

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#101]
Thumbnails missing in tinkbox several times for iphone 5& 6
![img_3817](https://cloud.githubusercontent.com/assets/10393619/8684117/e3937bbc-2a76-11e5-93f8-5d932ca89e69.PNG)

**Comment by shikarkhane** [comment]
Robert, do you think that the thumbnails sometimes don't load cause i am serving them from same app server and not from CDN?
Or is it a client side caching issue?

**Comment by shikarkhane** [comment]
I think this happens when images are being loaded from cache. For eg. i opened my mac and the existing page showed no thumbnails.

**Comment by rdougan** [comment]
fixed. it was happening when the trinket store wasn't loaded when the feed was being shown

https://github.com/shikarkhane/tt-sencha/pull/21
