### ISSUE TITLE
Send Tink View: Only subset of contacts showing

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#11]
Currently only contacts that are added in the phones contact list with a +(XX) prefix are shown in app. We need to handle the case were contacts are stored in the phone without this prefix, which will be very common. 

Action: Look at standard solution methodology in other apps using phone number as key key user identidicator. Can the "local context" for registered user be used to add +(XX) to contacts without this, i.e. if a user registers with Swedish +46, then +46 are added to all contacts in the phone book that are missing prefix.

**Comment by shikarkhane** [comment]
fixed
