### ISSUE TITLE
paging error

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#120]
1. Goto feed page
2. scroll to bottom and click and click more to go to second page.
3. now click left top corner button to get out of feed page and you end up in gallery page
4. now click top right corner button to go back to feed page. 
5. Now you are on feed page, at page number 2 but the back button is missing. So you cannot go to first page.

@rdougan can you please fix this bug.

**Comment by rdougan** [comment]
I tried reproducing this and it works as expected. Video: https://www.dropbox.com/s/2p7egafocbfa5pm/bug.mov?dl=0

**Comment by shikarkhane** [comment]
I can reproduce this bug always on my android phone HTC one
