### ISSUE TITLE
Tinkbox - Show contacts with most recent activity on top. 

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#124]
Sort tinkbox in the following order:
1. the friend whom last tink was sent to should be first ( if this info exists in client side session)
2. show rest sorted by most unread first.
for eg.
Luoise <- last sent tink
Martin, unread 4
James, unread 2
Arthur, unread 1
rest of friends in whatever order

**Comment by shikarkhane** [comment]
@rajesh-wedig I will send from server, sorted by unread count. But on client side u have to change it, to make "last sent to" user first.

One more reason for client side change is because of async calling, the tink sent is not saved on server before tinkbox gets the grouped feed.

**Comment by shikarkhane** [comment]
Tinkbox is now sorted by most unread first. Last sent tink change, pending on @rajesh-wedig
