### ISSUE TITLE
Tinkbox – smaller circle should be shown corresponding to either in or out depending on balance. Now bigger circle is always on the left. 

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#126]
If you have sent more then you have received it should be a bigger circle for sent and smaller for incoming. And the other way around. So we only have two different sizes of the circles as we have it no – but they are shifted on left or right side depending on the balance.

**Comment by shikarkhane** [comment]
@rajesh-wedig please fix this bug. Ask me if u have doubts, on skype

**Comment by shikarkhane** [comment]
This seems like a data bug. We will flush the whole database and re-test things.
