### ISSUE TITLE
Tinkfeed- 9 tinks are showing - I have an opened tink below those 9, so it looks as if I have a new tink all the time. Cannot open it since it is not accessible.

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#129]
Since only 9 tinks are showing rest is deleted, I cannot get rid of the indication that I have a new unopned tink. How should we handle this?

**Comment by shikarkhane** [comment]
@rdougan please implement paging as before, we will get it styled by offshore team later. The api already supports this.

**Comment by shikarkhane** [comment]
showing 1000 for the time being
