### ISSUE TITLE
Send Invite pop-up: Only "No" option showing, and change text

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#14]
There must be a Yes option.
And text must be changed to not only refer to "him". 

Suggestion: 
Pop-up title: "Invite?"
Text: "Your friend is currently not using Tinktime. Do you want to send an invite so that your friend can view your Tink?"

**Comment by shikarkhane** [comment]
Fixed. Now no and yes options available.

Text changed to 
"Invite?",
"Your friend is not using tinktime. Invite your friend to view this tink!",
