### ISSUE TITLE
Send Tink View: Contact Name not showing Correctly, using "null"

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#15]
In iPhone.

If contact added only with first name and no last name, Contact list showing "first name" + null, e.g.

Moni null

Should be only name added in Contact list showing, e.g. 

Moni

**Comment by shikarkhane** [comment]
Changed null to emptry string on server side.
I hope this is fixed.

**Comment by MonicaSylvander** [comment]
Null is still in contact list for Iphone 5&6
