### ISSUE TITLE
Red notification dot on Icon after push notification is stuck on 1 for Iphone. See attached screenshot. 

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#166]
So even if I get several new tinks it is still on 1. And even if I do not have any new tinks it is still on 1 even if have opened a tink. It is both for Iphone 5& 6. 
![screenshot red notification iphone](https://cloud.githubusercontent.com/assets/10393619/12719272/543506a8-c8f4-11e5-9052-f70c903e8ae8.png)

**Comment by shikarkhane** [comment]
We will clear the badge when the app is opened after notification. We will not deal with the exact count of unread links and badge count number for the time being. ( url is for developer's reference)
http://stackoverflow.com/questions/27311910/how-to-clear-badge-counter-on-click-of-app-icon-in-iphone
