### ISSUE TITLE
Add the welcome Tink with girl talking, and speach bubbles welcoming users

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#172]

**Comment by shikarkhane** [comment]
We need a thumbnail for this welcome animation.
Please add it to the Tink animations folder on google drive, so we have everything at one place

**Comment by shikarkhane** [comment]
Added welcome trinket to animations from back office.

Hardcoded welcome trinket to pick the abovementioend animation.

Changes will reflect on server deploy. Marking this as fixed
