### ISSUE TITLE
Tink View: Time must be shown more Clear

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#18]
- Time shall be shown in larger - see mockups
- Show time in a semi-transparent box overlay, so that time is always visible no matter tink animation design. This is preferred. See attached example. 
- Time shall be slightly moved upp from current placement.

**Comment by MonicaSylvander** [comment]
Also Time should be moved up slightly.

**Comment by shikarkhane** [comment]
We should keep this one for later. Cause we need to first verify how the app looks on different devices.

Moreover there has to be consistency in showing time on different screens. Should all screens have time inside a circle?

**Comment by MonicaSylvander** [comment]
No, not in circle. (actually the attached example is not that good, I was more reffering to the overlay and not the circle) We think it should be in a box/icon at the top.  We see it as a box/icon with round edges with time inside. But yes, let us get back to this later.

**Comment by shikarkhane** [comment]
Fixed in ui milestone
