### ISSUE TITLE
tinkbox: Play Tink function does not work properly

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#20]
Play Tink shall start in full screen mode just like in Tink view
Time overlay needs to be fixed in same way as in Tink view to make the time more clear
Message needs to be shown more clear: We need to discuss options:
- Show message using semi-transparent overlay in bottom all time during Tink is played
- Show message like above but together with time overlay.
- Or only show message in tinkbox, after tink has been played.

**Comment by shikarkhane** [comment]
replay shows relavant tink with correct sec and test message
