### ISSUE TITLE
Send Tink & Tinkbox - contact list sometimes show in blue underline style  (like a link) Same in Tinkbox. 

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#27]
Send Tink - Contact list: sometimes the phone number is shown in blue underline style (like a link). 
Tinkbox: Same  defect exist in Tinkbox.

**Comment by shikarkhane** [comment]
Don't see this in android. 

Please attach a screenshot of phone when you get this.

**Comment by MonicaSylvander** [comment]
No it just appeared again. See attachment from Tinkbox. And I just realized that it is the phone number instead of the contact name. Next time I entered it looked normal again. So it only appears sometimes. 
![img_0810](https://cloud.githubusercontent.com/assets/10393619/7400733/58e29202-eebf-11e4-9228-cab1720d5c38.PNG)

**Comment by MonicaSylvander** [comment]
And this is an example from the contact list. 
![img_0811](https://cloud.githubusercontent.com/assets/10393619/7400887/53a1a20a-eec0-11e4-8d09-608d1bbe6347.PNG)

**Comment by shikarkhane** [comment]
I presume this is fixed in UI milestone
