### ISSUE TITLE
Verify Number - Separate "box" to choose Country - country code automatically added. 

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#32]
Change way of adding phone number. Separate "box" to chose country - and country code automatically added. Phone number can be added with or without starting "0", UI recongnizes and puts starting zero in brackets, "(0)", e.g. (0)733335720

**Comment by shikarkhane** [comment]
fixed. Styling will be done later.

prefix of 0 or not, i am not sure if its applicable to all countries or not.
