### ISSUE TITLE
Send Tink - Contact list - Contacts registered with Tinktime must be shown differently

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#40]
Contact list: Contacts registered with Tinktime must be shown differently so that is is clear to the user that that contact is with Tinktime. Suggest: Add smaller font under contact name with "I am using Tinktime" (like in Whatsapp).

**Comment by shikarkhane** [comment]
I have made contacts on tinktime to be in green and not in red. We can play with this UI in future.
