### ISSUE TITLE
Send Tink - Contact list - handle contacts with multiple phone numbers

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#43]
Add all numbers from phone contacts. Meaning if a given contact has home, mobile, work phone numbers. Then add all of them to contacts list with prefix "Home" , "Mobile" accordingly.

Suggestion: Store the dial code of authenticated phonenumber and use that to pre-fix phone numbers without dial code.

**Comment by rdougan** [comment]
https://github.com/shikarkhane/tt-sencha/pull/15

**Comment by shikarkhane** [comment]
If a contact has 3 phone numbers, then its showing 3 numbers in contacts list alright but they are same number repeating.

**Comment by rdougan** [comment]
fixed. though I've noticed that the phone_type is being sent to the server, but not returned (when checking if they are on tinktime).
