### ISSUE TITLE
Compose Tink - New design on Tink button when pressed

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#44]
Tink button needs to have another design when pressed to indicate being pressed. Very Important for the feeling of the app. Do something similar to Snapchat, with button growing slightly, and changes color of middle area in Tinkbutton to the coral (orange/red) color we are using for buttons.

**Comment by shikarkhane** [comment]
Monica, May be you can ask one of your animators to fix this one.
Give them the tink logo and they should give you back css code with animation.

**Comment by MonicaSylvander** [comment]
Yes, good idea! I will do that.

/Monica

**Comment by shikarkhane** [comment]
fixed. It is a variation of what the designer has provided.
