### ISSUE TITLE
Split- Screen - Make thumb look like in Tinkbox and send tink

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#45]
Tink Thumb icon shall not be divided into two colors divided by vertical line. Make thumb icon look like in Send Tink and Tinkbox, with fixed transparency, and also with time showing. (We need to remember users are sending time - we cannot forgot this in this view).

**Comment by shikarkhane** [comment]
Fixed opacity of image, to remove separation line.

Created issue 64, as enhancement, to show seconds on image. ( since this was not in the mocks)
