### ISSUE TITLE
Text message design in tink playing

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#47]
For text message: Same as for time, have a semi transparent grey nuance box with white text, placed at the bottom where the Tink-button usually is placed. See attachement for an example on how the text box could look like.

**Comment by MonicaSylvander** [comment]
![message](https://cloud.githubusercontent.com/assets/10393619/7283789/41931b7a-e939-11e4-8d42-2143cb96d154.jpg)

**Comment by shikarkhane** [comment]
fixed
