### ISSUE TITLE
Verify number - keyboard pop-up should be only numbers - see attachement

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#57]
When you add your phone number it would be preferred to only have number key board as when you are adding a contact in your phone. See attachement as an example. 
![key board](https://cloud.githubusercontent.com/assets/10393619/7338967/3017e39e-ec5e-11e4-9d8f-0502f2ac7f5e.png)

**Comment by shikarkhane** [comment]
I believe this is fixed now.
