### ISSUE TITLE
tinkbox - paging 

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#65]
implement paging  on tink box

**Comment by shikarkhane** [comment]
Right now, i am loading only last 10 msgs. 

Work in progress.

**Comment by rdougan** [comment]
i updated the code to make the list infinite, so it should just handle 100s if not 1000s of feed entries. so you can make the server return more than 10.

one downside to this is that the item height needs to be fixed. i believe this is OK, but let me know.

**Comment by shikarkhane** [comment]
client is calling the api which offers page no and size of page. But your latest PR is not triggering second page request and further.

**Comment by shikarkhane** [comment]
Moreover, with even 10 messages, i am not able to scroll and see all the msgs till the end on HTC One.

**Comment by rdougan** [comment]
how do you want this to look? next page button at the bottom?

**Comment by rdougan** [comment]
also, can you return the total amount of messages in the response? then we can show/hide the next/previous buttons only when required.

**Comment by shikarkhane** [comment]
I 1

**Comment by rdougan** [comment]
@shikarkhane that will not work. that is basically what i was using for the infinite list. you will still have the same performance issue on android. Plus you need a fixed item height for it to work well.

**Comment by shikarkhane** [comment]
Ok lets do buttons for mvp.

Can you make the previous and next buttons part of the feed. Eg. last message while scrolling is next button and scrolling up is previous button if on 2nd or onward page.

**Comment by rdougan** [comment]
I just added a PR to make those buttons at the top and bottom.

Still need the total count so the next button can hide/show only when needed

**Comment by rdougan** [comment]
Oh a unrelated note: i suggest you remove the begin landing screen when you are already logged in
