### ISSUE TITLE
Design in all pages needs to be modified to not overlay phone top icon bar symbols

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#7]
Content needs to start lower in all screens so not put over or very close to the standard phone icons top bar.

But the standard background should be coverring the full screen as now. There will be different fixes needed pending page:
- Begin page: No changes needed
- Verify number: title text "Verify Number" needs to be moved down
- Verification code: title text "Verification Code" needs to be moved down
- Trinket View: Dog ear showing Tinkbox needs to be changed so that envelope is lower and not mixed with phone top bar symbols. Preferred solution: make dog ear larger, still starting from top, and move envelope down
- Tink view: same as above for dog ear. Plus top left tink icon needs to move down to the same height as the envelope.
- send tink view: the "Cancel button" (circle with cross) in the top right needs to move down to same level as other moved down symbols. THis mean that the "To" field also will move down.
- Sent Tink split view page: same as before: envelope and tink symbol needs to move down.
- Tinkbox: Top right envelope needs to move down same way as above. Plus top left dog ear needs to be modified in the same way as the top right dog ear as described above, so that the tink symbol can move down and not be put over the phone top icon bar symbols. Plus, the "tinkbox" title text needs to be put down.

**Comment by shikarkhane** [comment]
This was a problem with iOS and is fixed now.
