### ISSUE TITLE
Contacts prefix: when abroad all contacts that does not have a prefix gets added the prefix that is in that country. 

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#76]
All my contacts that did not have a prefix got added +31 in my contact list.

**Comment by MonicaSylvander** [comment]
Not the case anymore! Trying it in Italy - not the local prefix added. So this one is sorted out! But instead it is Null as the prefix for those I do not have any added prefix for.

**Comment by shikarkhane** [comment]
Closing this since we have another opened for this specifically.
