### ISSUE TITLE
Verify number: Wrong prefix added to my phone number abroad, so I could not download the app. (Iphone6)

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#78]
I tried to download Tinktime abroad, I added +46 when verifying my number, and everything looked right, but at the next view it had automtically changed to the local prefix +31. So I never got the SMS. This was only for Iphone 6 - it worked for iPhone 5. I tried several times. See attachement. 
![verify number abroad](https://cloud.githubusercontent.com/assets/10393619/7669712/6aaf01fc-fc82-11e4-9acf-4a36c8b383f4.png)

**Comment by shikarkhane** [comment]
fixed

**Comment by aastha252** [comment]
switchoff karke on karle
