### ISSUE TITLE
Prio - 01 Contacts search is slow on android

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#83]
Android HTC one ( Android 5.0.2 - API 21) , contacts search is very slow. 
As compared to iOS, its very slow.

**Comment by rdougan** [comment]
Testing this on an Android HTC One x, running android 4.2.2 - and the search is performing fine. How many contacts do you have?

**Comment by shikarkhane** [comment]
I have more than 500 contacts.

How abt the rendering everytime a new letter is edited. Is that optimized?

**Comment by rdougan** [comment]
OK. I will switch it to use the infinite list so that only ~10 items are rendered. Hopefully that will fix the issue, as there is few little else we can do (easily).

**Comment by rdougan** [comment]
implemented in this list: https://github.com/shikarkhane/tt-sencha/pull/14
