### ISSUE TITLE
Glitches and non-smooth transitions

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#84]
When moving back and forth between different screens, there is visible re-rendering happening. 
Looks not so smooth. 

eg.
Go back and forth between tink gallery and tink page.

**Comment by rdougan** [comment]
Can you update the tinket HTML so it has `body { background: transparent' }`? It will hopefully stop it flashing when it loads.

**Comment by shikarkhane** [comment]
Tried background transparent, didnt work. I have applied it on DJ cat animation. ( red thumbnail with cat w headphones)

**Comment by rdougan** [comment]
This should be fixed

**Comment by shikarkhane** [comment]
We will call this fixed for the time being. Way better than before.

But on android htc one (Android 5.0.2 - API 21), one still sees small re-rendering when switching between gallery page and feed page. But we will get back to this after this milestone is done.
