### ISSUE TITLE
 Time-box - not centered (Iphone) which is disturbing and feels to low disturbing the animation. 

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#86]
Suggestion: Time-box - not centered which is disturbing and feels to low disturbing the animation. Suggestion: 
As a top bar (to minimize disturbing the animation) - see attachement. 
Color: #777777
Opacity: 70%
![time new](https://cloud.githubusercontent.com/assets/10393619/8129011/eac5850a-1104-11e5-9e36-278d66a03d5b.jpg)

**Comment by shikarkhane** [comment]
I am still keeping the time floating on top of animation when thinking. But i have center aligned it.

We need to discuss this further, cause in my recent demo to a friend, he didn't seem to bother about the time but was more interested to reach the end of animation. So moving the time to top bar would even make it more obsolete. hence, the need for discussion.
