### ISSUE TITLE
Message box - same color as for timebox. Color: #777777 Opacity: 70%

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#87]
4. Message box - same color as for timebox.
Color: #777777
Opacity: 70%
![time new](https://cloud.githubusercontent.com/assets/10393619/8129023/0fcf7978-1105-11e5-89fc-f851b057a2de.jpg)

**Comment by shikarkhane** [comment]
Please clarify, whicj message box are you refering to ? the attached image confuses me even further

**Comment by MonicaSylvander** [comment]
Issue is concerning the color of the transparent overlay-area containing the message in recieved tink. The color should be the same as for the time box overlay. So the transparent overlay should be: Color: #777777 Opacity: 70%

**Comment by shikarkhane** [comment]
Fixed.
