### ISSUE TITLE
Prio - 03 Pre-load active selected animation

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#92]
As soon as user selects an animation ( i.e. from tink gallery) we should download that animation already.

Cause it seems like right now, a heavy animation which hasn't been downloaded takes time to start when user has already pressed the thinking button. So the user sees the clock running 3-4 seconds before anything happens.

**Comment by rdougan** [comment]
I've actually already implemented this a few weeks ago. I just tested it and it definitely appears to be loading the content before the user starts thinking.
