### ISSUE TITLE
Prio - 04 Contacts local store 

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#93]
Right now, everytime app loads, the whole contacts data is getting refreshed. Then the client sends the data to the server to check who is on tinktime or not.

Here there are some issues:
1. sometimes the phonenumber to username lookup is not done before user clicks on feed page. Hence, shows phonenumber instead of names in the feed. 
2. contacts client side store is getting refreshed completely. Is this how other apps do it? There should be a better way than this.

**Comment by rdougan** [comment]
1. i changed the logic to wait until the contacts has been processed until processing the feed
2. on iOS, i would just sync the contacts - but this isn't built into sencha touch. I think the best way forward is to just optimise the way we process the contacts so it is as fast as possible
