### ISSUE TITLE
Loading wheel while feed loads

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#94]
Since we wait to load feed page till the contacts to name mapping completes, we should add loading wheel.

**Comment by rdougan** [comment]
https://github.com/shikarkhane/tt-sencha/pull/15

**Comment by shikarkhane** [comment]
This doesn't work always. I will get back on exact steps to reproduce

**Comment by shikarkhane** [comment]
On android,
1. open the app, verify yourself and then get out of the app
2. go to all active apps list, drag out the tinktime app. I don't know if it is same as force stopping the app
3. Open the tinktime app again and go to feed page. Now you don't get any progress wheel.

**Comment by rdougan** [comment]
i updated the loading/masking flow a little in general. i can't reproduce this issue anymore.

https://github.com/shikarkhane/tt-sencha/pull/21
