### ISSUE TITLE
Send invite via ams flow is broken

### ISSUE THREAD

**Issue by shikarkhane** [shikarkhane/tt#98]
When someone tries to send tink to someone who is not on tinktime network ( a red contact in contacts list on send page), app asks if you want to send sms to invite.

Please try it out and you will know right away all the broken parts.

**Comment by rdougan** [comment]
So what should the flow be?

- user tries to send tink, contact not on tinktime.
- user is prompted to send sms

Then:

- user sends successfully or
- user cancels sending sms

..now what? Can tinktime not send the SMS?

**Comment by shikarkhane** [comment]
i got this one
